### ISSUE TITLE
Provide methods for traversal of address maps

### ISSUE THREAD

**Issue by mpriestleyidex** [krcb197/PeakRDL-python#47]
Presently there's no way (I think?) of asking an address map to give you all the registers (or memories or sub address maps) within it.
I think in the same way that registers have the `readable_fields` and `writable_fields` generators, you could provide generators on addressmaps such as `registers` `memories` and `addressmaps` to allows the tree to be traversed.

Presumably this would also help with #37

**Comment by krcb197** [comment]
Seems like a good idea, I can see two ways:

1. A regfile/address map has a `readable_fields` generator that calls through to any child register generators
2. A regfile/address map has a `readable_register` generator that calls through to registers

What makes sense

**Comment by mpriestleyidex** [comment]
I don't think "get me all the fields under this address map" is something you'd often want to do. I think it's more helpful to provide the means for traversing the tree.

Perhaps if I show what I'm trying to achieve; the following code (with suitable modifications to the exporter) walks the address map and checks every field's reset value. It requires no knowledge of what's in the address map (other than to ignore things I know I can't check).

```
# Register testing

excluded_fields = [
    ("GPIO", "GPIO_IN", "GPIO_INPUT"),          # Reflects live input
    ("PRNG", "PRNG_RESULT", "PRNG_RESULT"),     # Updates on every read
]

def reg_check_defaults(reg):
    fvals = reg.read_fields()
    for f in reg.readable_fields :
        if f.default is not None and \
        (f.parent.parent.inst_name, f.parent.inst_name, f.inst_name) not in excluded_fields :
            assert fvals[f.inst_name] == f.default, \
                f"{f.full_name} expected {f.default} got {fvals[f.inst_name]}"


def addrmap_check_defaults(addrmap):
    print(f"Check {addrmap.inst_name}")

    for reg in addrmap.registers :
        if isinstance(reg, tuple):
            for r in reg :
                if not is_unreadable(addrmap, r) :
                    reg_check_defaults(r)
        else:
            if not is_unreadable(addrmap, reg) :
                reg_check_defaults(reg)

    for amap in addrmap.addressmaps :
        if isinstance(amap, tuple):
            for m in amap :
                addrmap_check_defaults(m)
        else:
            addrmap_check_defaults(amap)
```

Some other potential niceties come up here:

- Providing a `parent` property of the `Base` class, such that you can always go upwards from any node or field
- Should the generators unroll arrays of instances rather than returning tuples?
  - Maybe an optional `unroll` argument, like SystemRDL-compiler has?
- For instances within arrays, should `inst_name` (or another property) include the suffix ("MYREG[0]" vs "MYREG")?

(I appreciate this could be seen as a slippery slope, at the bottom of which you'd have been better off using SystemRDL-compiler directly!)

**Comment by mpriestleyidex** [comment]
BTW I'm happy to contribute changes, and have been prototyping similar in a branch of a fork:
https://github.com/idex-biometrics/PeakRDL-python/tree/experimental

**Comment by krcb197** [comment]
@mpriestleyidex I am really pleased someone else has taken an interest in my project and I welcome contributions, I am happy to credit anyone who has made a contribution.

I have had a quick look at what you have done on there, can I suggest you have a separate branch for:

- the iterator enhancements 
- the default value (reset)
- the other properties

I think these change are somewhat independent and more easily discussed as separate items. 

One of the concerns is that each field instance can have different reset values rather than it being part of the class definition.I would prefer not to put them in the `FieldSizeProps` class, I think the reset value is another type of data and shouldn't really get combined into the `FieldSizeProps`. I have started looking at this problem myself. I had some code as a work in progress anyway.

As a note, re: _I appreciate this could be seen as a slippery slope, at the bottom of which you'd have been better off using SystemRDL-compiler directly_ Some organisations have strict security rules about IC code (including the systemRDL) which means that can't be shared with wider software teams, that was one of my motivations for doing this project in the first place as the python wrapper can be built and then distributed without needing to distribute any of the IC code. Therefore I think it is worth enhancing the wrappers with the types of iterators you suggest.

**Comment by shareefj** [comment]
@krcb197 What happened to the changes merged here?  They seem to have disappeared and I can't easily find a replacement for their functionality?  You seem to have lost all the `get_*` getters and the `addrmap.childen` iterator.  Is there now no way of iterating over all registers aside from calling `get_readable_registers` and `get_writeable_registers` in sequence?

**Comment by krcb197** [comment]
@shareefj 

This ticket was closed last year having implemented several iterators that allow the entire address map to be traversed in a structured manner. 

There is a section in the documentation that covers this: [Walking the Strucrture](https://peakrdl-python.readthedocs.io/en/latest/generated_package.html#walking-the-structure) along with several supporting examples see: [Examples - Traversing Address Map](example/tranversing_address_map). 

If you have a specific use case in mind that is not served well and you think some more features need to be added, it would be best to open a new issue rather than extend this one.
